/**
 * A policy trained on demonstrations, running in the browser.
 *
 * Three thousand parameters and two hidden layers, which is small enough that
 * what ships is arithmetic rather than a runtime — no framework, no WASM, and
 * the weights are a JSON file anyone can open and read.
 *
 * What it was trained on is stated rather than implied. The demonstrations are
 * machine-generated by a scripted controller driving the station's own
 * dynamics, because the on-chain corpus is not yet coherent enough to learn
 * from: twenty of its thirty-five recordings report the jaws closed while the
 * tool is two hundred millimetres from the payload, and a network trained on
 * those learns that reaching does not matter. That is a fact about how the
 * corpus was filled — largely by my own test scripts — and not about the
 * pipeline, which this exists to show does work.
 */

export type Policy = {
  arch: { in: number; hidden: number; out: number };
  params: number;
  trainedOn: { episodes: number; frames: number; heldOutEpisodes: number };
  loss: { train: number; heldOut: number };
  rollout: {
    starts: number; grasped: number; placedAndReleased: number;
    medianFinalMm: number; toleranceMm: number; note: string;
  };
  mean: number[]; std: number[];
  W1: number[][]; b1: number[];
  W2: number[][]; b2: number[];
  W3: number[][]; b3: number[];
};

let cached: Promise<Policy> | null = null;

/** Fetched once, on demand. Sixty-five kilobytes is not something to spend on
 *  a page nobody asked to see the policy on. */
export function loadPolicy(): Promise<Policy> {
  cached ??= fetch("/policy.json").then((r) => {
    if (!r.ok) throw new Error("The policy weights are not available.");
    return r.json() as Promise<Policy>;
  });
  return cached;
}

const relu = (v: number[]) => v.map((x) => (x > 0 ? x : 0));

/**
 * What the policy would do next.
 *
 * The observation is deliberately relative — where the payload is *from the
 * tool*, where the goal is *from the payload* — so the network cannot memorise
 * the one datum every task on this bench shares and pass it off as a policy.
 *
 * Returns a tool delta in metres and the jaw state it wants.
 */
export function act(
  p: Policy,
  tool: readonly [number, number, number],
  object: readonly [number, number, number],
  goal: readonly [number, number],
  gripMm: number,
): { delta: [number, number, number]; close: boolean } {
  const raw = [
    tool[0], tool[1], tool[2],
    object[0] - tool[0], object[1] - tool[1], object[2] - tool[2],
    goal[0] - object[0], goal[1] - object[1], 0 - object[2],
    gripMm > 14 ? 0 : 1,
  ];
  const x = raw.map((v, i) => (v - p.mean[i]) / p.std[i]);
  const a1 = relu(p.W1.map((w, i) => w.reduce((s, wv, j) => s + wv * x[j], p.b1[i])));
  const a2 = relu(p.W2.map((w, i) => w.reduce((s, wv, j) => s + wv * a1[j], p.b2[i])));
  const y = p.W3.map((w, i) => w.reduce((s, wv, j) => s + wv * a2[j], p.b3[i]));
  // The trainer scaled deltas by 100 so a 20 Hz step was not sub-millimetre
  // noise the network would learn to answer with zero.
  return { delta: [y[0] / 100, y[1] / 100, y[2] / 100], close: y[3] > 0.5 };
}
