import type { Metadata } from "next";
import { AskPanel } from "@/components/ask-panel";
import Link from "next/link";
import spec from "@/lib/arm-spec.json";
import { NON_CAPABILITIES } from "@/lib/chain";
import { DimRule } from "@/components/primitives";

export const metadata: Metadata = {
  title: "THENAR-6 — spec sheet",
  description:
    "The six-axis arm the station drives, generated from a parametric Python kernel. Every dimension here is the constant the geometry was built from.",
};

/**
 * Every figure on this page is read from lib/arm-spec.json, which cad/arm.py
 * writes at export time. There is no second copy of these numbers to drift.
 */
export default function SpecPage() {
  const closed = spec.part_report.filter((p) => p.closed).length;

  return (
    <div className="mx-auto max-w-[900px] px-5 py-10">
      <h1 className="font-display text-[clamp(2.4rem,6vw,3.6rem)] font-700 leading-[0.96] tracking-[-0.02em]">
        THENAR-6
      </h1>
      <p className="mt-4 max-w-[62ch] text-[16px] leading-relaxed text-scribe-2">
        A six-axis arm with a parallel-jaw gripper. There is no CAD file — the
        geometry is generated by a {spec.parts}-part Python kernel using numpy
        alone, with no CSG booleans, and every part is validated as a closed
        surface before it is exported. Change a constant, rerun the script, and
        the arm, this page, and the solver all move together.
      </p>

      <div className="mt-8 grid grid-cols-2 gap-px bg-rule sm:grid-cols-4">
        <Cell label="Axes" value={String(spec.axes)} />
        <Cell label="Reach" value={`${spec.reach_mm} mm`} />
        <Cell label="Height" value={`${spec.height_mm} mm`} />
        <Cell label="Jaw stroke" value={`${spec.gripper.stroke_mm} mm`} />
      </div>

      <DimRule className="mt-12" note="Link dimensions" />
      <table className="mt-5 w-full border-collapse">
        <thead>
          <tr className="border-b border-rule-strong">
            <th scope="col" className="label pb-2 text-left font-normal">Link</th>
            <th scope="col" className="label pb-2 text-left font-normal">Constant</th>
            <th scope="col" className="label pb-2 text-right font-normal">Value</th>
            <th scope="col" className="label pb-2 pl-6 text-left font-normal">Spans</th>
          </tr>
        </thead>
        <tbody>
          {spec.links.map((l) => (
            <tr key={l.symbol} className="border-b border-rule">
              <td className="py-2.5 text-[14px]">{l.name}</td>
              <td className="py-2.5 font-mono text-[12px] text-scribe-3">{l.symbol}</td>
              <td className="py-2.5 text-right font-mono text-[14px] tabular-nums text-signal">
                {l.value_mm.toFixed(1)}
                <span className="ml-1 text-[12px] text-scribe-3">mm</span>
              </td>
              <td className="py-2.5 pl-6 text-[13px] text-scribe-2">{l.note}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <DimRule className="mt-12" note="Kinematic chain" />
      <ul className="mt-5 flex flex-col">
        {spec.joints.map((j, i) => (
          <li key={j.id} className="flex flex-wrap items-baseline gap-x-5 border-b border-rule py-2.5">
            <span className="w-[92px] shrink-0 font-mono text-[13px] text-scribe">{j.id}</span>
            <span className="w-[52px] shrink-0 font-mono text-[12px] text-signal">axis {j.axis}</span>
            <span className="text-[14px] text-scribe-2">{j.drives}</span>
            <span className="ml-auto font-mono text-[12px] text-scribe-3">
              {i === spec.joints.length - 1 ? "tool flange" : `→ ${spec.joints[i + 1].id}`}
            </span>
          </li>
        ))}
      </ul>
      <p className="mt-4 max-w-[62ch] text-[14px] leading-relaxed text-scribe-2">
        The GLB ships as a named node hierarchy rather than one welded mesh, which
        is what lets the station drive each joint straight from the inverse
        kinematics solver instead of playing a baked animation.
      </p>

      <DimRule className="mt-12" note="Export" />
      <div className="mt-5 grid grid-cols-2 gap-px bg-rule sm:grid-cols-4">
        <Cell label="Parts" value={String(spec.parts)} />
        <Cell label="Triangles" value={spec.triangles.toLocaleString()} />
        <Cell label="GLB size" value={`${Math.round(spec.glb_bytes / 1024)} KB`} />
        <Cell
          label="Closed surfaces"
          value={`${closed} / ${spec.part_report.length}`}
          tone={closed === spec.part_report.length ? "go" : "reject"}
        />
      </div>

      <details className="mt-5 border border-rule">
        <summary className="cursor-pointer px-4 py-2.5 font-mono text-[12px] uppercase tracking-[0.12em] text-scribe-3 hover:text-scribe">
          Per-part validation
        </summary>
        <ul className="grid grid-cols-2 gap-x-6 border-t border-rule px-4 py-3 sm:grid-cols-3">
          {spec.part_report.map((p) => (
            <li key={p.part} className="flex items-baseline justify-between gap-3 py-1 font-mono text-[12px]">
              <span className="truncate text-scribe-2">{p.part}</span>
              <span className="shrink-0 tabular-nums text-scribe-3">{p.triangles}</span>
              <span className={p.closed ? "text-go" : "text-reject"}>{p.closed ? "closed" : "OPEN"}</span>
            </li>
          ))}
        </ul>
      </details>

      <DimRule className="mt-12" note="Finish" />
      <ul className="mt-5 flex flex-wrap gap-4">
        {spec.materials.map((m) => (
          <li key={m.key} className="flex items-center gap-3 border border-rule px-3 py-2">
            <span className="size-6 border border-rule-strong" style={{ background: m.color }} aria-hidden="true" />
            <span className="flex flex-col">
              <span className="font-mono text-[12px] capitalize text-scribe">{m.key}</span>
              <span className="font-mono text-[12px] text-scribe-3">
                {m.color} · m{m.metallic} r{m.roughness}
              </span>
            </span>
          </li>
        ))}
      </ul>

      <p className="mt-12 max-w-[62ch] text-[14px] leading-relaxed text-scribe-3">
        Regenerate everything on this page with{" "}
        <code className="text-scribe-2">python3 cad/arm.py</code>. It writes the
        GLB the viewport loads, one STL per printable part, and the JSON this
        page reads.
      </p>

      <Link
        href="/hub"
        className="mt-8 inline-block border border-scribe bg-scribe px-5 py-2.5 font-mono text-[12px] uppercase tracking-[0.16em] text-ink-0 transition-colors hover:border-signal-hi hover:bg-signal-hi"
      >
        Put it to work
      </Link>

      <DimRule className="mt-14" note="Signing without a seed phrase" />
      <p className="mt-4 max-w-[62ch] text-[15px] leading-relaxed text-scribe-2">
        Monad carries the P-256 precompile at 0x0100, so a signature from the
        curve a passkey uses can be checked on chain directly. The registry binds
        one to an address, and a run can be authorised with it.{" "}
        <Link href="/passkey" className="text-signal hover:text-signal-hi">Register a passkey &rarr;</Link>
      </p>

      <DimRule className="mt-14" note="Ask the instrument" />
      <p className="mt-4 max-w-[62ch] text-[15px] leading-relaxed text-scribe-2">
        Not a chatbot. Every answer below is read from the constant the scorer
        actually uses and says where it came from, and a question it cannot
        answer exactly is refused rather than approximated &mdash; which is the
        whole reason the list is short.
      </p>
      <div className="mt-5">
        <AskPanel />
      </div>

      <DimRule className="mt-14" note="What this is not" />
      <p className="mt-4 max-w-[62ch] text-[15px] leading-relaxed text-scribe-2">
        An arm moving in a browser invites a few assumptions. These are the ones
        that are wrong, stated here rather than left to be discovered. They are
        roadmap, and nothing in the interface presents them as working.
      </p>
      <ul className="mt-5 flex flex-col">
        {NON_CAPABILITIES.map((n) => (
          <li key={n.title} className="flex flex-col gap-1 border-b border-rule py-3.5">
            <span className="font-mono text-[13px] uppercase tracking-[0.12em] text-reject">
              {n.title}
            </span>
            <span className="max-w-[70ch] text-[14px] leading-relaxed text-scribe-3">{n.body}</span>
          </li>
        ))}
      </ul>

      {/* The first of those is the one a buyer of this corpus is entitled to put
          a number on, so it has one. Saying "kinematic, not rigid-body" and
          leaving it there asks the reader to guess how much fidelity that costs;
          this says how the answer is obtained and where to read it per run. */}
      <p className="mt-6 max-w-[70ch] text-[14px] leading-relaxed text-scribe-2">
        The first of those is measured rather than left as a caveat. Every
        recorded run is handed to{" "}
        <span className="font-mono text-[13px] text-scribe">MuJoCo</span> as the
        same release state and integrated to rest under rigid-body dynamics; the
        distance between where the recording put the payload and where physics
        would have is published on that run&rsquo;s own page. It scores nothing
        and changes no payout — it exists so the gap is a figure rather than an
        assumption.{" "}
        <Link href="/run/0x77f0cc8cd166ce38679fee669324dc3b898ed308dbf7aee8752c96490941a7a2" className="text-signal hover:text-signal-hi">
          See it on a run
        </Link>
        .
      </p>
    </div>
  );
}

function Cell({ label, value, tone }: { label: string; value: string; tone?: "go" | "reject" }) {
  return (
    <div className="flex flex-col gap-1 bg-ink-1 px-4 py-3">
      <span className="label">{label}</span>
      <span
        className={`font-mono text-[16px] tabular-nums ${
          tone === "go" ? "text-go" : tone === "reject" ? "text-reject" : "text-scribe"
        }`}
      >
        {value}
      </span>
    </div>
  );
}
